ARG rustver
ARG imagever

FROM rust:${rustver} AS build
COPY . /build
WORKDIR /build
RUN apt-get update && apt-get upgrade -y && apt-get install libssl-dev pkg-config -y
RUN cargo build --release

FROM debian:${imagever}
RUN apt-get update && apt-get upgrade -y && apt-get install libssl3 -y
COPY --from=build /build/target/release/jet /usr/bin/
