@echo off

rem Auto-generated by jet expand
rem Edit at your own peril!

if not defined JAVA_HOME (
    goto java_home_not_defined
)

goto good

:java_home_not_defined
echo JAVA_HOME environment variable must be defined

:good
"%JAVA_HOME%/bin/java" -Xmx$$JAVA_MEM$$ -Xms$$JAVA_MEM$$ $$JAVA_GC_OPTS$$ -jar $$SERVER_JAR$$ nogui
