#!/bin/bash

# Auto-generated by jet expand
# Edit at your own peril!

if [ "$JAVA_HOME" -e "" ]; then
    echo JAVA_HOME must be set
fi

if ! $JAVA_HOME/bin/java -version | grep -Eq "version \"17.+?\""; then
    echo JAVA_HOME may not point to a valid version of java
    $JAVA_HOME/bin/java -version
fi

$JAVA_HOME/bin/java -Xmx$$JAVA_MEM$$ -Xms$$JAVA_MEM$$ $$JAVA_GC_OPTS$$ $$JAVA_EXTRA_OPTS$$ -jar $$SERVER_JAR$$ nogui
