name: Docker

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: |
          docker build -f Dockerfile.debian --tag ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID}-bookworm --build-arg="rustver=slim" --build-arg="imagever=bookworm" .
          docker build -f Dockerfile.debian --tag ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID}-bookworm-slim --build-arg="rustver=slim" --build-arg="imagever=bookworm-slim" .
          docker build -f Dockerfile.alpine --tag ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID}-alpine --build-arg="rustver=alpine" --build-arg="imagever=latest" .
          
          docker tag ghcr.io/${{ github.repository_owner }}/jet ghcr.io/${{ github.repository_owner }}/jet:${GITHUB_RUN_ID}-alpine
          docker tag ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID} ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID}-alpine
          docker tag ghcr.io/${{ github.repository_owner }}/jet:bookworm ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID}-bookworm
          docker tag ghcr.io/${{ github.repository_owner }}/jet:bookworm-slim ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID}-bookworm-slim
          docker tag ghcr.io/${{ github.repository_owner }}/jet:alpine ghcr.io/${{ github.repository_owner }}/jet:v${GITHUB_RUN_ID}-alpine
          
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          
          docker push ghcr.io/der-fruhling/jet
          docker push ghcr.io/der-fruhling/jet:bookworm
          docker push ghcr.io/der-fruhling/jet:bookworm-slim
          docker push ghcr.io/der-fruhling/jet:alpine
          docker push ghcr.io/der-fruhling/jet:v${GITHUB_RUN_ID}
          docker push ghcr.io/der-fruhling/jet:v${GITHUB_RUN_ID}-bookworm
          docker push ghcr.io/der-fruhling/jet:v${GITHUB_RUN_ID}-bookworm-slim
          docker push ghcr.io/der-fruhling/jet:v${GITHUB_RUN_ID}-alpine
